apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
        - name: service-d
          image: service-d:1.0.0
          ports:
            - containerPort: 9200
        - name: proxy-b
          image: service-mesh-proxy:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: LOCAL_SERVICE_NAME
              value: "service-d"
            - name: LOCAL_SERVICE_PORT
              value: "9200"
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
spec:
  selector:
    app: service-d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
