apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      containers:
        - name: control-plane
          image: service-mesh-control-plane:1.0.0
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane-service
spec:
  selector:
    app: control-plane
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
